alias n='npm'
alias ni='npm install'
alias nis='npm install --save'
alias nid='npm install --save-dev'
alias nig='npm install --global'
alias nu='npm uninstall'
alias nus='npm uninstall --save'
alias nud='npm uninstall --save-dev'
alias nug='npm uninstall --global'
alias nl='npm list'
alias nl0='npm list --depth 0'
alias nl1='npm list --depth 1'
alias nlg='npm list -g'
alias nlg0='npm list -g --depth 0'
alias nlg1='npm list -g --depth 1'

